### ISSUE TITLE
PDF for Shipment / CreditMemo?

### ISSUE THREAD

**Issue by Ph1975** [firegento/firegento-pdf2#1]
Hi guys,

is there any chance that Firegento-pdf2 will be developed any further, especially regarding Packslip/Shipment and also Creditmemo as PDF?

Thanks in advance,
Philipp

**Comment by sprankhub** [comment]
There is currently not really a template for an invoice as well - I think it just says "Hello World" or something allike :D

This was a project on a hackathon, where we started to port the PDF extension to M2. Even though I think we will implement it at some time, there is no schedule and no guarantee when/that it will be implemented.

You can of course consider sponsoring the development :-)
