### ISSUE TITLE
does this extension work? ;)

### ISSUE THREAD

**Issue by dni** [firegento/firegento-pdf2#2]
ist it firegento pdf for magento2 like it was for magento1? this repository seems kind of inactive.

**Comment by sprankhub** [comment]
I think currently, you should be able to get a test PDF with it :-) Sorry, it is not in a usable state. We started the project at a hackathon and never worked on it any more. I am not sure if it will be in a usable state in the near future :-/

**Comment by dni** [comment]
nooo, a pity, liked the extension very much for 1.9, now i'm back to the ugly looking standard pdfs.

**Comment by sprankhub** [comment]
One of the "issues" with this extension is that there are multiple very good paid alternatives:

- https://store.fooman.co.nz/extensions/magento2/magento-extension-pdf-customiser-m2.html
- https://www.xtento.com/magento-extensions/magento-pdf-customizer-extension.html
- https://www.vianetz.com/de/magento-extensions/magento-2/advancedinvoicelayout-magento-2.html

So there is no big win when developing this :-)

**Comment by dni** [comment]
in my opinion it would be of great benefit, because 

1. it goes very well with the magesetup extension
2. the paid alternatives are looking good but also very bloated, while this one is very simply and still does the job
3. the hassle of creating an account and registering a LICENSE key for multiple customers.

i would rather pay for the development of this extension than buying a licensed one.

**Comment by dni** [comment]
how much would it cost to sponsor the development? i can maybe also help, with some guide

**Comment by sprankhub** [comment]
Of course this is your personal preference, but I still want to say something regarding your points :-)

1. We do nothing special regarding MageSetup. AFAIK, MageSetup works with the paid versions as well.
2. I do not think that the paid alternatives are really bloated. Of course they have more features, but this is not necessarily a bad thing.
3. This is our normal work, isn't it? :-) By the way, [Private Packagist](https://packagist.com/) really comes in handy with this.

Thanks for the offer to sponsor the development! In general, we as FireGento decided against paying people to develop our modules. But maybe a sponsorship would still work.
But please mind that a module like this takes thousands of euros to develop. Not sure if this is an option for you.

Additionally, there are many things, which need to be decided. For instance, I am not quite sure if we should follow the old PHP approach to generate the PDFs or if we should better use a HTML to PDF library like the one, which we included during our test ([dompdf](https://github.com/dompdf/dompdf)).

**Comment by dni** [comment]
thank you very much for the feedback, not really an option for me though, that would break the budget.
thanks for the hint of private packagist.

i would vote for the old approach, till the magento2 devs decide to do better themselves ;). And maybe even threw this topic at them and let them decide or ask if they have planned anything?
